DELETE FROM `creature_template` WHERE `entry`=46962;
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `femaleName`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `exp_unk`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Mana_mod_extra`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) VALUES (46962, 49708, 0, 0, 0, 0, 34610, 0, 0, 0, 'Baron Ashbury', '', '', '', 0, 21, 21, 0, 0, 16, 0, 1, 1.42857, 1, 1, 28, 38, 0, 68, 1.7, 1500, 2000, 2, 32832, 2048, 0, 0, 0, 0, 0, 0, 19, 29, 4, 7, 72, 0, 46962, 0, 0, 0, 0, 0, 0, 0, 0, 93423, 93812, 93757, 0, 0, 0, 0, 0, 0, 1422, 0, 0, 'SmartAI', 0, 3, 1, 25, 10, 1, 1, 0, 0, 0, 0, 0, 0, 0, 144, 1, 46962, 617299803, 3, 'boss_baron_ashbury', 1);
DELETE FROM `creature_template` WHERE `entry`=49708;
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `femaleName`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `exp_unk`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Mana_mod_extra`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) VALUES (49708, 0, 0, 0, 0, 0, 34610, 0, 0, 0, 'Baron Ashbury', '', '', '', 0, 87, 87, 3, 0, 16, 0, 1, 1.14286, 1, 1, 713, 920, 0, 992, 30, 1500, 2000, 2, 0, 2048, 0, 0, 0, 0, 0, 0, 477, 682, 159, 7, 72, 0, 49708, 0, 0, 0, 0, 0, 0, 0, 0, 93710, 93423, 93812, 93757, 0, 0, 0, 0, 0, 1422, 9966, 26633, '', 0, 3, 1, 50, 124, 1, 1, 0, 0, 0, 0, 0, 0, 0, 144, 1, 46962, 617299803, 3, '', 1);



-- Generated by Event Horizon - SAI Editor (http://devsource-eventhorizon.tk/)

-- Baron Ashbury
SET @ENTRY := 46962;
SET @SOURCETYPE := 0;

DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=@SOURCETYPE;
UPDATE creature_template SET AIName="SmartAI" WHERE entry=@ENTRY LIMIT 1;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES 
(@ENTRY,@SOURCETYPE,0,0,4,0,100,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Say Text on Aggro"),
(@ENTRY,@SOURCETYPE,1,0,0,0,100,0,2000,4500,18000,20000,11,93581,0,0,0,0,0,5,0,0,0,0.0,0.0,0.0,0.0,"Cast Pain and Suffering"),
(@ENTRY,@SOURCETYPE,2,0,0,0,100,4,2000,4500,18000,20000,11,93712,0,0,0,0,0,5,0,0,0,0.0,0.0,0.0,0.0,"Cast Pain and Suffering"),
(@ENTRY,@SOURCETYPE,3,7,0,0,100,0,12000,12000,40000,40000,11,93423,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Cast Asphyxiate"),
(@ENTRY,@SOURCETYPE,4,8,0,0,100,4,12000,12000,40000,40000,11,93710,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Cast Asphyxiate"),
(@ENTRY,@SOURCETYPE,5,9,0,0,100,0,19000,19000,47000,47000,11,93468,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Cast Stay of Execution"),
(@ENTRY,@SOURCETYPE,6,10,0,0,100,4,19000,19000,47000,47000,11,93705,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Cast Stay of Execution"),
(@ENTRY,@SOURCETYPE,7,0,61,0,100,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Say Text on Cast Asphyxiate"),
(@ENTRY,@SOURCETYPE,8,0,61,0,100,4,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Say Text on Cast Asphyxiate"),
(@ENTRY,@SOURCETYPE,9,11,61,0,100,0,0,0,0,0,1,2,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Say Boss Text on Cast Stay of Execution"),
(@ENTRY,@SOURCETYPE,10,12,61,0,100,4,0,0,0,0,1,2,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Say Boss Text on Cast Stay of Execution"),
(@ENTRY,@SOURCETYPE,11,0,61,0,100,0,0,0,0,0,1,3,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Say Text on Cast Stay of Execution"),
(@ENTRY,@SOURCETYPE,12,0,61,0,100,4,0,0,0,0,1,3,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Say Text on Cast Stay of Execution"),
(@ENTRY,@SOURCETYPE,13,0,0,0,100,4,20000,20000,120000,120000,11,93720,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Cast Wracking Pain"),
(@ENTRY,@SOURCETYPE,14,15,2,0,100,5,0,20,0,0,11,93757,1,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Cast Dark Archangel Form at 20% HP"),
(@ENTRY,@SOURCETYPE,15,16,61,0,100,5,0,0,0,0,11,93812,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Cast Calamity at 20% HP"),
(@ENTRY,@SOURCETYPE,16,0,61,0,100,5,0,0,0,0,1,4,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Say Text on Cast Calamity at 20% HP"),
(@ENTRY,@SOURCETYPE,17,0,6,0,100,1,0,0,0,0,1,5,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Say Text on Death");